plugins {
    id 'com.android.application'
}

android {
    namespace 'com.karpardaz.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.karpardaz.app"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("release.jks")
            storePassword "123456"
            keyAlias "karpardaz"
            keyPassword "123456"
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}
